#!/bin/bash
USBDEFAULT="/usr/local/lib/usbguardian/usb_default"
USBUNKNOWN="/usr/local/lib/usbguardian/usb_unknown"
USBLIBFOLDER="/usr/local/lib/usbguardian/"
USBSBINFOLDER="/usr/local/sbin/usbguardian/"
ATINPUT="/usr/local/lib/usbguardian/atinout-input.txt"
ATOUTPUT="/usr/local/lib/usbguardian/atinout-output.txt"
ATIOUTEXE="/usr/local/sbin/usbguardian/atinout/atinout"
ATINOUTFOLDER="/usr/local/sbin/usbguardian/atinout"
#Remove usb_default configuration
if [ -f $USBDEFAULT ]
then
	rm $USBDEFAULT
fi

#Remove usb_unknown configuration
if [ -f $USBUNKNOWN ]
then
	rm $USBUNKNOWN
fi

#Remove AT input data configuration
if [ -f $ATINPUT ]
then
        rm $ATIINPUT
fi

#Remove AT output data configuration
if [ -f $ATOUTPUT ]
then
        rm $ATOUTPUT
fi

if [ -d $USBLIBFOLDER ]
then
	rm -r $USBLIBFOLDER
fi

#Remove Atinout executable and folder

if [ -e $ATINOUTEXE ]
then
        rm  $ATINOUTEXE
fi

if [ -d $ATINOUTFOLDER ]
then
        rm -r $ATINOUTFOLDER
fi

#Remove sbin usbguardian folder
if [ -d $USBSBINFOLDER ]
then
	rm -r $USBSBINFOLDER
fi


ListaPuertos=$(ls /dev/ | egrep tty'[0-9]{1,4}')
for I in $ListaPuertos
do
     echo "Enabling getty#"$I
     systemctl enable getty@$I

done
