#!/bin/bash
USBDEFAULT="/usr/local/lib/usbguardian/usb_default"
USBUNKNOWN="/usr/local/lib/usbguardian/usb_unknown"
USBFOLDER="/usr/local/lib/usbguardian/"

#Remove usb_default configuration
if [ -f $USBDEFAULT ]
then
	rm $USBDEFAULT
fi

#Remove usb_unknown configuration
if [ -f $USBUNKNOWN ]
then
	rm $USBUNKNOWN
fi

rm -r $USBFOLDER

